[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

float-cmp = "0.9.0"
cstr = "0.2.11"
image = { version = "0.25", features = ["jpeg", "png"] }
rand = "0.8.5"