[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

float-cmp = "0.9.0"
raylib = "3.7.0"
cstr = "0.2.11"
image = "0.25.0"